addr: "127.0.0.1:8000"
filter_plugin_dir: ""
predicate_plugin_dir: ""
 
routes_file: "../config/routes.yml"
services_file: "../config/services.yml"

max_idle_conns: 40000
max_idle_conns_per_host: 20000

access_log_file: "./access.log"
enable_https: false

admin_domain: "127.0.0.1"
admin_port: "7004"

admin_name: "admin"
admin_pass: "admin"

